
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\gathi\Desktop\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1434x948")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 948,
    width = 1434,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    32.0,
    115.0,
    994.0,
    755.0,
    fill="#D9D9D9",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    493.0,
    432.0,
    image=image_image_1
)

canvas.create_text(
    389.0,
    238.0,
    anchor="nw",
    text="RD TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    286.0,
    456.0,
    anchor="nw",
    text="RR1 TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    286.0,
    498.0,
    anchor="nw",
    text="RR2 TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    286.0,
    561.0,
    anchor="nw",
    text="RR3 TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    260.0,
    658.0,
    anchor="nw",
    text="15-0 TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    597.0,
    591.0,
    anchor="nw",
    text="RD2 TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    784.0,
    727.0,
    anchor="nw",
    text="Write Data TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    555.0,
    459.0,
    anchor="nw",
    text="RD1 TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    471.0,
    420.0,
    anchor="nw",
    text="RW TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    510.0,
    279.0,
    anchor="nw",
    text="J TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    505.0,
    298.0,
    anchor="nw",
    text="B TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    513.0,
    315.0,
    anchor="nw",
    text="MR TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    513.0,
    332.0,
    anchor="nw",
    text="MtR TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    494.0,
    351.0,
    anchor="nw",
    text="ALUO TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    597.0,
    365.0,
    anchor="nw",
    text="MW TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_text(
    588.0,
    415.0,
    anchor="nw",
    text="ALUS TB",
    fill="#000000",
    font=("Inter", 14 * -1)
)

canvas.create_rectangle(
    999.0,
    115.0,
    1416.0,
    941.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    32.0,
    760.0,
    994.0,
    941.0,
    fill="#D9D9D9",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    513.5,
    850.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=38.0,
    y=766.0,
    width=951.0,
    height=166.0
)

canvas.create_rectangle(
    311.0,
    32.0,
    1111.0,
    87.0,
    fill="#D9D9D9",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=341.0,
    y=39.0,
    width=40.0,
    height=40.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=481.4000244140625,
    y=39.0,
    width=40.0,
    height=40.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=621.7999877929688,
    y=39.0,
    width=40.0,
    height=40.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=762.199951171875,
    y=38.99999999999999,
    width=40.0,
    height=40.00000000000001
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=902.5999755859375,
    y=39.0,
    width=40.0,
    height=40.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=1043.0,
    y=39.0,
    width=40.0,
    height=40.0
)

canvas.create_rectangle(
    1275.0,
    115.0,
    1416.0,
    132.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    999.0,
    115.0,
    1138.0,
    132.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    1137.0,
    115.0,
    1276.0,
    132.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    1331.5,
    117.0,
    anchor="nw",
    text="Value",
    fill="#000000",
    font=("Inter", 10 * -1)
)

canvas.create_text(
    1188.5,
    117.0,
    anchor="nw",
    text="Number",
    fill="#000000",
    font=("Inter", 10 * -1)
)

canvas.create_text(
    1054.5,
    117.0,
    anchor="nw",
    text="Name",
    fill="#000000",
    font=("Inter", 10 * -1)
)
window.resizable(False, False)
window.mainloop()
